
version: "3.8"
  
services:

  character-api-database-mysql:
    image: mysql:latest
    container_name: character-api-database-mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
        reservations:
          cpus: '0.25'
          memory: 150M
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=welcome
    
  character-api:
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
        reservations:
          cpus: '0.25'
          memory: 150M
    ports:
      - 9080:9080
    depends_on: 
      - character-api-database-mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      