
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.cache: DEBUG
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG

spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
      
  datasource:
    url: jdbc:mysql://localhost:3306/characterdb
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    hikari:
      maximum-pool-size: 10
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.EhCacheRegionFactory
      net.sf.ehcache.configurationResourceName: META-INF/ehcache.xml
      hibernate.generate_statistics: true
      hibernate.jdbc.wrap_result_sets: true
      hibernate.jdbc.batch_size: 20
      hibernate.default_batch_fetch_size: 4

  liquibase:
    change-log: classpath:liquibase/create-tables.xml
    default-schema: characterdb

  data:
    rest:
      base-path: /api/v1
      
api:
  pagination:
    default-page-number: 0
    default-page-size: 10
