
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.cache: DEBUG
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG

spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
      
  data:
    rest:
      base-path: /api/v1