
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.cache: DEBUG
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG

spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
      
  datasource:
    url: jdbc:mysql://localhost:3306/characterdb?createDatabaseIfNotExist=true
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
    
server:
  port: 9080
      